[package]
name = "roop"
edition.workspace = true
version.workspace = true

[[bin]]
name = "roop"
path = "src/main.rs"

[dependencies]
serde_json = "1"
roop-syntax = { path = "../roop-syntax" }
roop-check = { path = "../roop-check" }
roop-opt = { path = "../roop-opt" }
roop-llvm = { path = "../roop-llvm" }
roop-config = { path = "../roop-config" }
roop-lean = { path = "../roop-lean" }
roop-modules = { path = "../roop-modules" }
roop-fmt = { path = "../roop-fmt" }
