mod check;
mod check_ancilla;
mod check_block;
mod check_update;
mod error;
mod expr_places;
mod expr_vars;
mod inverts;
mod pending;
mod place_index_reads;
mod place_path;
mod place_root;
mod place_vars;
mod places_overlap;
mod stmt_reads;
mod stmt_writes;

use check_ancilla::check_ancilla;
use check_block::check_block;
use check_update::check_update;
use expr_places::expr_places;
use expr_vars::expr_vars;
use inverts::inverts;
use pending::Pending;
use place_index_reads::place_index_reads;
use place_path::place_path;
use place_root::place_root;
use place_vars::place_vars;
use places_overlap::places_overlap;
use stmt_reads::stmt_reads;
use stmt_writes::stmt_writes;

pub use check::check;
pub use error::CheckError;
