//! A compiler from a model of reversible layers to roop code that runs it
//! forward and backward with weave, and to the tests that check that code
//! against a reference in doubles.

mod activation;
mod batch_sample;
mod batch_suffix;
mod contraction_bound;
mod decl;
mod emit_backward;
mod emit_batch_tests;
mod emit_driver;
mod emit_forward;
mod emit_grad;
mod emit_load;
mod emit_main;
mod emit_model;
mod emit_project;
mod emit_step;
mod emit_tests;
mod emit_train;
mod gradient_unit;
mod gradients;
mod layer;
mod layer_call;
mod load_helper;
mod loss;
mod loss_kind;
mod model;
mod names;
mod near;
mod norm_spec;
mod optimizer;
mod param_list;
mod parse_model;
mod quantize;
mod reference;
mod residual_iterations;
mod sample;
mod spectral_norm;
mod state_type;
mod tensor;
mod weave_error;

pub use activation::*;
pub use batch_sample::*;
pub use batch_suffix::*;
pub use contraction_bound::*;
pub use decl::*;
pub use emit_backward::*;
pub use emit_batch_tests::*;
pub use emit_driver::*;
pub use emit_forward::*;
pub use emit_grad::*;
pub use emit_load::*;
pub use emit_main::*;
pub use emit_model::*;
pub use emit_project::*;
pub use emit_step::*;
pub use emit_tests::*;
pub use emit_train::*;
pub use gradient_unit::*;
pub use gradients::*;
pub use layer::*;
pub use layer_call::*;
pub use load_helper::*;
pub use loss::*;
pub use loss_kind::*;
pub use model::*;
pub use names::*;
pub use near::*;
pub use norm_spec::*;
pub use optimizer::*;
pub use param_list::*;
pub use parse_model::*;
pub use quantize::*;
pub use reference::*;
pub use residual_iterations::*;
pub use sample::*;
pub use spectral_norm::*;
pub use state_type::*;
pub use tensor::*;
pub use weave_error::*;
